# PostgreSQL configuration for Rails
# Requires pg gem installed

default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: book_buddy_development

test:
  <<: *default
  database: book_buddy_test

production:
  primary: &primary_production
    <<: *default
    database: book_buddy_production
    username: <%= ENV.fetch("BOOK_BUDDY_DB_USERNAME", "book_buddy") %>
    password: <%= ENV["BOOK_BUDDY_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: book_buddy_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: book_buddy_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: book_buddy_production_cable
    migrations_paths: db/cable_migrate
