# PostgreSQL configuration for Rails
# Requires pg gem installed

default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: book_buddy_development

test:
  <<: *default
  database: book_buddy_test

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    url: <%= ENV["DATABASE_URL"] %>
